import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "environment"
        }
      ]
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "ai-responses"
        },
        {
          "slug": "conversation-memory"
        },
        {
          "slug": "documentation-lookup"
        },
        {
          "slug": "messaging-bot"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
